[project]
version = "0.1.0"
name = "sysinfo"
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
protonerf = "1"
buffer = "1"
slice = "1"
err = "1"
hex = "1"
log = "1"
time = "1"
madpack = "1"
