os:
  - osx
  - linux
language: rust

rust:
  - nightly

cache: cargo

script:
  - ci/ci.sh

deploy:
  provider: releases
  api_key:
    secure: uSnISz/IhlmHZOuuaiw3iVeptfmMdvgVzPsdzrZ5dNakhVXu/r/fEMkPAoxfqWgxyYoBV9NGR41LQ7t9/tRVSnz6yUyRZmgLEe4grJLXckMLT53RsdOs4lBpJBSG1Vwx4KSAQ+bjEjzTPoqrXoOCbi9J82F8er0ExFktyIxnecM9ZG2cEenUqE9Qm6445jlJLdBsLtxhAhHTvMnqOLtmfSNfxKimn6YFSIfvu2PIqaur30NlSphJBF2XhXx1L99guq3SgWWmeCVjQqpd02TDpoCE16jIAPlIh8it+NJ2DucDSjj9XWKqIrO3M7tU2NcCrfodBDlD0m1P7mBm3nFmzZr27536KIrlVn7u7xu2U1bNHw7J8vv2ECkn0dHu+eGRzFcgtHbE9PJNzTeZuOuAhwtLEwWoaBb/BHc3TiCcvzlts88q91wvS027z3CJb+2T+HynQmDevrsGsbEO463k9NZi2fZBbvFskPftzuHtnNNzt6sdL8eGjpGW1VDstaw7tYaUVjjs0HkuPBSPQ6pUe81uCFw2swjHXyy2cIRNhKpWnHtl4k3loks8FJWljAcafwYy2mXzO7hx85Z3zS3IX+NGfbrCxB2D9DPZBZ4K3yjNnkCg2HgAHbjG3RIPAabM9Zo1epbfnnw70Nv4GVtzHOWlflZoRfAQ4xoQiI1Sj6c=
  file: target/rsbuild/*
  file_glob: true
  draft: true
  skip_cleanup: true
  on:
    repo: devguardio/carrier
    tags: true

