[project]
version = "0.1.0"
name = "carrier"
cincludes = []
cobjects = [
    "3rdparty/hacl-star/snapshots/hacl-c/FStar.c",
    "3rdparty/hacl-star/snapshots/hacl-c/kremlib.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Ed25519.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Curve25519.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_SHA2_256.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_HMAC_SHA2_256.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Chacha20Poly1305.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Chacha20.c",
    "3rdparty/hacl-star/snapshots/hacl-c/AEAD_Poly1305_64.c",
    "3rdparty/hacl-star/snapshots/hacl-c/Hacl_Policies.c",
]
pkgconfig = []
cflags = [ "-D", "KRML_NOUINT128", "-Os"]
lflags = []

[dependencies]
err         = "1"
hex         = "1"
mem         = "1"
byteorder   = "1"
hpack       = "1"
net         = "1"
string      = "1"
json        = "1"
log         = "1"
protonerf   = "1"
pool        = "1"
toml        = "1"
fs          = "1"
sysinfo     = "1"

[variants]
default = []

[[artifacts]]
type     = "esp32"
name     = "carrier"
main     = "carrier::esp32"
requires = ["spi_flash", "bootloader_support", "app_update"]

[[artifacts]]
type = "lib"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "rust"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "python"
name = "carrier"
main = "carrier::python"

[[artifacts]]
type = "cmake"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "exe"
name = "carrier"
main = "carrier::main"

[repos]
nursery = "git://github.com/zetzit/nursery.git"
#nursery = "/home/aep/proj/zznursery"

