[project]
version = "0.13.0"
name = "carrier"
cincludes = [
    "3rdparty/hacl-star/dist/kremlin/include/",
    "3rdparty/hacl-star/dist/kremlin/kremlib/dist/minimal/",
]
cobjects = [
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Chacha20Poly1305_32.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Hash.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Ed25519.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Curve25519_51.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Poly1305_32.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Chacha20.c",
]
pkgconfig = []
cflags = [ "-D", "KRML_NOUINT128", "-g"]
lflags = ["-lpthread", "-g"]

[dependencies]
err         = "1"
mem         = "1"
err         = "1"
slice       = "1"
base32      = "1"
buffer      = "1"
hpack       = "1"

[variants]
default = []

[[artifacts]]
type = "rust"
name = "carrier"
main = "carrier"
