[package]
name = "cli"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
clap                = "2.32.0"
failure             = "0.1.2"
tokio               = "0.1.7"
futures             = "0.1"
prost               = "0.4.0"
log                 = "0.4.3"
rand                = "0.5"
env_logger          = "0.5.12"
ox                  = {path = "../ox"}
serde               = "1.0"
serde_derive        = "1.0"
toml                = "0.4"
trust-dns-resolver  = "0.10.0-alpha.2"
url                 = "1.7.1"
hpack               = "0.3.0"
