[project]
version = "0.13.0"
name = "carrier"
cincludes = [
    "3rdparty/hacl-star/dist/kremlin/include/",
    "3rdparty/hacl-star/dist/kremlin/kremlib/dist/minimal/",
]
cobjects = [
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Chacha20Poly1305_32.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Hash.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Ed25519.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Curve25519_51.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Poly1305_32.c",
    "3rdparty/hacl-star/dist/gcc-compatible/Hacl_Chacha20.c",
]
pkgconfig = []
cflags = [ "-D", "KRML_NOUINT128", "-g"]
lflags = ["-lpthread", "-g"]

[dependencies]
err         = "1"
hex         = "1"
mem         = "1"
byteorder   = "1"
hpack       = "1"
net         = "1"
buffer      = "1"
json        = "1"
log         = "1"
protonerf   = "1"
pool        = "1"
toml        = "1"
fs          = "1"
sysinfo     = "1"
base32      = "1"
io          = "1"
netio       = "1"
madpack     = "1"

[repos]
#madpack = "git://github.com/aep/madpack.git"

[variants]
default = []

[[artifacts]]
type     = "esp32"
name     = "carrier"
main     = "carrier::esp32"
requires = ["spi_flash", "bootloader_support", "app_update"]

[[artifacts]]
type = "lib"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "rust"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "python"
name = "carrier"
main = "carrier::python"

[[artifacts]]
type = "npm"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "go"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "cmake"
name = "carrier"
main = "carrier"

[[artifacts]]
type = "exe"
name = "carrier"
main = "carrier::main"

[[artifacts]]
type = "make"
name = "carrier-openwrt"
main = "carrier::openwrt"

