name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]



    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0


    - name: prep-macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install z3
        wget http://bin.zetz.it.s3-eu-west-1.amazonaws.com/zz-master-macos.zip
        unzip zz*.zip

    - name: prep-ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y z3
        wget http://bin.zetz.it.s3-eu-west-1.amazonaws.com/zz-master-ubuntu.zip
        unzip zz*.zip

    - name: build
      run: |
        export "PATH=$PATH:$PWD/target/release/"
        cd core
        zz clean
        zz test
        cd ../go
        go test
        cd ../cli
        go test

    #- name: Snapshot
    #  if: matrix.os == 'ubuntu-latest'
    #  run: |
    #    export "PATH=$PATH:$PWD/target/release/"
    #    git config --local user.email "snapbot@devguard.io"
    #    git config --local user.name "Snapshot Bot"
    #    git add go/core -f
    #    git commit -m "snapshot"


    #- name: Push changes
    #  if:   matrix.os == 'ubuntu-latest'
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}

