[package]
name = "wsx"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
ws = "0.7.8"
log = "0.4.4"
env_logger = "0.5.13"
carrier-core = {path = "../core/"}
trust-dns-resolver = "0.9.1"
mio     = "0.6"
mio-extras = "2.0.5"
failure = "0.1.2"
